### ISSUE TITLE
transforms.Normalize() is not  working in teacher training file 

### ISSUE THREAD

**Issue by aryanasadianuoit** [shriramsb/Distilling-the-Knowledge-in-a-Neural-Network#1]
In distill_basic_teacher.ipynb, for both training_dataset and test_dataset, the transform.Normalize has been set wrongly. The mentioned transform converts the input image to the shape (2,28,28).

**Comment by shriramsb** [comment]
replacing `transforms.Normalize((0.5, 0.5), (0.5, 0.5))` to `transforms.Normalize([0.5], [0.5])` fixes the issue.
